[versions]
kotlin = "1.9.24"
compose-bom = "2024.06.00"
room = "2.6.1"
hilt = "2.51"
coroutines = "1.8.1"
billing = "7.0.0"
integrity = "1.3.0"
security-crypto = "1.1.0-alpha06"
lifecycle = "2.8.1"
work = "2.9.0"
navigation-compose = "2.7.7"

[libraries]
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
billing-ktx = { module = "com.android.billingclient:billing-ktx", version.ref = "billing" }
play-integrity = { module = "com.google.android.play:integrity", version.ref = "integrity" }
security-crypto = { module = "androidx.security:security-crypto", version.ref = "security-crypto" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
activity-compose = { module = "androidx.activity:activity-compose", version = "1.9.0" }

[plugins]
android-application = { id = "com.android.application", version = "8.5.0" }
android-library = { id = "com.android.library", version = "8.5.0" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
